name: Movie Picture Backend

on:
  pull_request:
    branches:
      - main
    path:
      - '../../starter/backend/**'
  
  workflow_dispatch:

defaults:
  run:
    working-directory: ./starter/backend 


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6'

      - name: Install pipenv
        run: pip install pipenv

      - name: Cache Pipenv
        uses: actions/cache@v3
        with:
          path: |
            ~/.pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run the linter.
        run: pipenv run lint


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.6'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run tests
        run:  pipenv run test

