name: Movie Picture Backend

on:
  pull_request:
    branches:
      - main
    path:
      - '../../starter/backend/**'
  
  workflow_dispatch:

defaults:
  run:
    working-directory: ./starter/backend 


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: action-python/pyinstaller-py3.7@amd64
        with:
          node-version: '16'

      - name: Install dependencies
        run: pipenv install

      - name: Run lint
        run: pipenv run lint


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: action-python/pyinstaller-py3.7@amd64
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run:  pipenv run test

